# ASP.NET Core (.NET 6)
# Build and publish an ASP.NET Core project using the .NET Core CLI tasks.
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  projectPath: 'pipeline-dotNet/pipelines-dotnet-core.csproj'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
  displayName: 'Install .NET 6 SDK'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(projectPath)'
  displayName: 'Restore'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(projectPath)'
    arguments: '--configuration $(buildConfiguration) --no-restore'
  displayName: 'Build'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '$(projectPath)'
    arguments: '--configuration $(buildConfiguration) --no-build --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true
  displayName: 'Publish'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish artifact'
